# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'att.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1520, 960)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QProgressBar {\n"
"    text-align: center;\n"
"    font: bold 15px;\n"
"    color: #000000;\n"
"    border: 1px solid transparent;\n"
"    border-radius:6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #c2c2c2, stop:0.5 #707070, stop:1 #d6d6d6);\n"
"    border-radius: 6px;\n"
"}\n"
"QProgressBar:disabled {\n"
"    color: #616161;\n"
"}\n"
"QProgressBar::chunk:disabled {\n"
"    background-color: #aeaeae;\n"
"}\n"
"\n"
"QPushButton, QToolButton, QCommandLinkButton{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #333333, stop:1 #8c8c8c);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #333333, stop:0.5 #919191, stop:1 #333333);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #333333, stop:1 #8c8c8c);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #333333, stop:0.5 #919191, stop:1 #333333);\n"
"    border-width: 2px;\n"
"    border-radius: 6px;\n"
"    color: #616161;\n"
"    font-weight: bold;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #333333, stop:0.5 #919191, stop:1 #333333);\n"
"}\n"
"QPushButton::default, QToolButton::default, QCommandLinkButton::default{\n"
"    border: 6px solid transparent;\n"
"    color: #616161;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #dedede, stop:1 #dedede);\n"
"}\n"
"QPushButton:hover, QToolButton:hover, QCommandLinkButton:hover{\n"
"    color: #3d3d3d;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #303030, stop:0.5 #9c9c9c, stop:1 #333333);\n"
"     border-right-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #303030, stop:0.5 #919191, stop:1 #303030);\n"
"     border-left-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #303030, stop:0.5 #919191, stop:1 #303030);\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed, QCommandLinkButton:pressed{\n"
"    border-radius: 6px;\n"
"    color: #616161;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #303030, stop:0.5 #7a7a7a, stop:1 #303030);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #303030, stop:0.5 #7a7a7a, stop:1 #303030);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #303030, stop:0.5 #7a7a7a, stop:1 #303030);\n"
"}\n"
"QPushButton:disabled, QToolButton:disabled, QCommandLinkButton:disabled{\n"
"    border: 6px solid transparent;\n"
"    color: #dedede;\n"
"    color:#333333;\n"
"    padding: 0 5px 0 5px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #333333, stop:1 #8c8c8c);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #333333, stop:0.5 #616161, stop:1 #333333);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #333333, stop:1 #8c8c8c);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #333333, stop:0.5 #616161, stop:1 #333333);\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #333333, stop:0.5 #666666, stop:1 #333333);\n"
"}\n"
"\n"
"\n"
"QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QTimeEdit, QDateEdit, QDateTimeEdit, QListWidget, QComboBox, QGroupBox{\n"
"\n"
"\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border: 2px solid  transparent;\n"
"   \n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #737373, stop:1 #333333);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #333333, stop:1 #8c8c8c);\n"
"    border-left-color: #333333;\n"
"    border-right-color: #333333;\n"
"\n"
"    margin-right:4px;\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QTimeEdit:focus, QDateEdit:focus, QDateTimeEdit:focus, QComboBox:focus {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #adadad, stop:1 #707070);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #adadad, stop:1 #707070);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #adadad, stop:1 #707070);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #adadad, stop:1 #707070);\n"
"\n"
"}\n"
"\n"
"QLineEdit:disabled, QTextEdit:disabled, QPlainTextEdit:disabled, QSpinBox:disabled, QDoubleSpinBox:disabled, QTimeEdit:disabled, QDateEdit:disabled, QDateTimeEdit:disabled , QComboBox:disabled{\n"
"    color: #b9b9b9;\n"
"}\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button, QTimeEdit::up-button, QDateEdit::up-button, QDateTimeEdit::up-button , QComboBox::up-button{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 5px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    padding:10px;\n"
"}\n"
"\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button, QTimeEdit::down-button, QDateEdit::down-button, QDateTimeEdit::down-button, QComboBox::down-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    width: 5px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-bottom-right-radius: 3px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed, QDoubleSpinBox::up-button:pressed, QTimeEdit::up-button:pressed, QDateEdit::up-button:pressed, QDateTimeEdit::up-button:pressed {\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #7a7a7a, stop:0.5 #303030, stop:1 #7a7a7a);\n"
"}\n"
"QSpinBox::down-button:pressed, QDoubleSpinBox::down-button:pressed, QTimeEdit::down-button:pressed, QDateEdit::down-button:pressed, QDateTimeEdit::down-button:pressed {\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #7a7a7a, stop:0.5 #303030, stop:1 #7a7a7a);\n"
"}\n"
"QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover, QTimeEdit::up-button:hover, QDateEdit::up-button:hover, QDateTimeEdit::up-button:hover, QComboBox::up-button:hover {\n"
"    color: #FFFFFF;\n"
"    border-top-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #9c9c9c, stop:1 #303030);\n"
"\n"
"}\n"
"QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover, QTimeEdit::down-button:hover, QDateEdit::down-button:hover, QDateTimeEdit::down-button:hover {\n"
"    color: #FFFFFF;\n"
"    border-bottom-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #303030, stop:1 #9c9c9c);\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow, QTimeEdit::up-arrow, QDateEdit::up-arrow, QDateTimeEdit::up-arrow {\n"
"    image: url(./img/up.png);\n"
"}\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow, QTimeEdit::down-arrow, QDateEdit::down-arrow, QDateTimeEdit::down-arrow {\n"
"    image: url(./img/down.png);\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"    max-height: 5px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 5px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #333333, stop:0.5 #616161, stop:1 #333333);\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-height: 10px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover, QScrollBar::handle:vertical:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #616161, stop:0.5 #9c9c9c, stop:1 #616161);\n"
"}\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    border: 2px transparent grey;\n"
"    border-radius: 4px;\n"
"    subcontrol-origin: margin;\n"
"    background: #b9b9b9;\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"    subcontrol-position: left;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal, QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QComboBox:editable, QComboBox:!editable, QComboBox::drop-down:editable, QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    margin-right:4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #303030, stop:1 #9c9c9c);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(./img/down.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid darkgray;\n"
"    border-radius: 8px;\n"
"    selection-background-color: #9c9c9c;\n"
"    selection-color: #272727;\n"
"    color: #272727;\n"
"    background: white;\n"
"}\n"
"\n"
"#gbox_source_code, #gbox_run_test, #gbox_fixed_code, #gbox_test_cases, #gbox_tested_lines, #gbox_test_completed, #gbox_statistics{\n"
"\n"
"\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #333333, stop:1 #616161);\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #333333, stop:1 #616161);\n"
"    border-left-color: #616161;\n"
"    border-right-color: #616161;\n"
"}\n"
"\n"
"#gbox_source_code, #gbox_run_test, #gbox_fixed_code, #gbox_test_cases, #gbox_tested_lines\n"
"{\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    padding-bottom:4px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(8, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gbox_source_code = QtWidgets.QGroupBox(self.page)
        self.gbox_source_code.setObjectName("gbox_source_code")
        self.gridLayout = QtWidgets.QGridLayout(self.gbox_source_code)
        self.gridLayout.setContentsMargins(8, 25, -1, 8)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_source_code = QtWidgets.QTextEdit(self.gbox_source_code)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_source_code.setFont(font)
        self.txt_source_code.setObjectName("txt_source_code")
        self.gridLayout.addWidget(self.txt_source_code, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.gbox_source_code)
        self.gbox_run_test = QtWidgets.QGroupBox(self.page)
        self.gbox_run_test.setMinimumSize(QtCore.QSize(120, 0))
        self.gbox_run_test.setMaximumSize(QtCore.QSize(98, 16777215))
        self.gbox_run_test.setAlignment(QtCore.Qt.AlignCenter)
        self.gbox_run_test.setFlat(False)
        self.gbox_run_test.setObjectName("gbox_run_test")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gbox_run_test)
        self.gridLayout_6.setContentsMargins(-1, 25, 4, 8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sp_test_cases_pool_count = QtWidgets.QSpinBox(self.gbox_run_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sp_test_cases_pool_count.sizePolicy().hasHeightForWidth())
        self.sp_test_cases_pool_count.setSizePolicy(sizePolicy)
        self.sp_test_cases_pool_count.setMinimumSize(QtCore.QSize(109, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sp_test_cases_pool_count.setFont(font)
        self.sp_test_cases_pool_count.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_test_cases_pool_count.setMinimum(1)
        self.sp_test_cases_pool_count.setMaximum(100)
        self.sp_test_cases_pool_count.setObjectName("sp_test_cases_pool_count")
        self.gridLayout_6.addWidget(self.sp_test_cases_pool_count, 0, 0, 1, 1)
        self.btn_import_code = QtWidgets.QPushButton(self.gbox_run_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_import_code.sizePolicy().hasHeightForWidth())
        self.btn_import_code.setSizePolicy(sizePolicy)
        self.btn_import_code.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn_import_code.setFont(font)
        self.btn_import_code.setObjectName("btn_import_code")
        self.gridLayout_6.addWidget(self.btn_import_code, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.gbox_run_test)
        self.gbox_fixed_code = QtWidgets.QGroupBox(self.page)
        self.gbox_fixed_code.setObjectName("gbox_fixed_code")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbox_fixed_code)
        self.gridLayout_2.setContentsMargins(8, 25, -1, 8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.list_fixed_code = QtWidgets.QListWidget(self.gbox_fixed_code)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.list_fixed_code.setFont(font)
        self.list_fixed_code.setObjectName("list_fixed_code")
        self.gridLayout_2.addWidget(self.list_fixed_code, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.gbox_fixed_code)
        self.gbox_test_cases = QtWidgets.QGroupBox(self.page)
        self.gbox_test_cases.setObjectName("gbox_test_cases")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbox_test_cases)
        self.gridLayout_3.setContentsMargins(8, 25, -1, 8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbx_test_case_name = QtWidgets.QComboBox(self.gbox_test_cases)
        self.cbx_test_case_name.setEditable(False)
        self.cbx_test_case_name.setObjectName("cbx_test_case_name")
        self.gridLayout_3.addWidget(self.cbx_test_case_name, 0, 0, 1, 1)
        self.list_test_cases = QtWidgets.QListWidget(self.gbox_test_cases)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.list_test_cases.setFont(font)
        self.list_test_cases.setObjectName("list_test_cases")
        self.gridLayout_3.addWidget(self.list_test_cases, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.gbox_test_cases)
        self.gbox_tested_lines = QtWidgets.QGroupBox(self.page)
        self.gbox_tested_lines.setObjectName("gbox_tested_lines")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbox_tested_lines)
        self.gridLayout_4.setContentsMargins(8, 25, -1, 8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.list_tested_code_line = QtWidgets.QListWidget(self.gbox_tested_lines)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.list_tested_code_line.setFont(font)
        self.list_tested_code_line.setObjectName("list_tested_code_line")
        self.gridLayout_4.addWidget(self.list_tested_code_line, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.gbox_tested_lines)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_support_cases = QtWidgets.QWidget()
        self.page_support_cases.setObjectName("page_support_cases")
        self.txt_support_case_support_case = QtWidgets.QLineEdit(self.page_support_cases)
        self.txt_support_case_support_case.setGeometry(QtCore.QRect(340, 70, 580, 30))
        self.txt_support_case_support_case.setObjectName("txt_support_case_support_case")
        self.checkbox_support_case_str = QtWidgets.QCheckBox(self.page_support_cases)
        self.checkbox_support_case_str.setGeometry(QtCore.QRect(930, 70, 70, 30))
        self.checkbox_support_case_str.setChecked(True)
        self.checkbox_support_case_str.setObjectName("checkbox_support_case_str")
        self.btn_support_case_add = QtWidgets.QPushButton(self.page_support_cases)
        self.btn_support_case_add.setGeometry(QtCore.QRect(1000, 70, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_support_case_add.setFont(font)
        self.btn_support_case_add.setObjectName("btn_support_case_add")
        self.btn_support_case_done = QtWidgets.QPushButton(self.page_support_cases)
        self.btn_support_case_done.setGeometry(QtCore.QRect(1060, 70, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_support_case_done.setFont(font)
        self.btn_support_case_done.setObjectName("btn_support_case_done")
        self.btn_support_case_clear_cases = QtWidgets.QPushButton(self.page_support_cases)
        self.btn_support_case_clear_cases.setGeometry(QtCore.QRect(340, 640, 751, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_support_case_clear_cases.setFont(font)
        self.btn_support_case_clear_cases.setObjectName("btn_support_case_clear_cases")
        self.lw_support_case_values = QtWidgets.QListWidget(self.page_support_cases)
        self.lw_support_case_values.setGeometry(QtCore.QRect(340, 110, 761, 521))
        self.lw_support_case_values.setObjectName("lw_support_case_values")
        self.stackedWidget.addWidget(self.page_support_cases)
        self.verticalLayout.addWidget(self.stackedWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.gbox_test_completed = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_test_completed.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.gbox_test_completed.setFont(font)
        self.gbox_test_completed.setTitle("")
        self.gbox_test_completed.setObjectName("gbox_test_completed")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gbox_test_completed)
        self.gridLayout_7.setContentsMargins(-1, 4, -1, 4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pb_test_rate = QtWidgets.QProgressBar(self.gbox_test_completed)
        self.pb_test_rate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_test_rate.setFont(font)
        self.pb_test_rate.setProperty("value", 0)
        self.pb_test_rate.setObjectName("pb_test_rate")
        self.gridLayout_7.addWidget(self.pb_test_rate, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.gbox_test_completed)
        self.gbox_statistics = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_statistics.setMinimumSize(QtCore.QSize(0, 42))
        self.gbox_statistics.setTitle("")
        self.gbox_statistics.setObjectName("gbox_statistics")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gbox_statistics)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(4, -1, 4, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.gbox_statistics)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lbl_branched_count = QtWidgets.QLabel(self.gbox_statistics)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_branched_count.setFont(font)
        self.lbl_branched_count.setObjectName("lbl_branched_count")
        self.horizontalLayout.addWidget(self.lbl_branched_count)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lbl_tested_line_count = QtWidgets.QLabel(self.gbox_statistics)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_tested_line_count.setFont(font)
        self.lbl_tested_line_count.setObjectName("lbl_tested_line_count")
        self.horizontalLayout.addWidget(self.lbl_tested_line_count)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.gbox_statistics)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.progressBar_coverage_rate = QtWidgets.QProgressBar(self.gbox_statistics)
        self.progressBar_coverage_rate.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.progressBar_coverage_rate.setFont(font)
        self.progressBar_coverage_rate.setProperty("value", 0)
        self.progressBar_coverage_rate.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_coverage_rate.setObjectName("progressBar_coverage_rate")
        self.horizontalLayout.addWidget(self.progressBar_coverage_rate)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.gbox_statistics)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1520, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport_Report = QtWidgets.QAction(MainWindow)
        self.actionExport_Report.setObjectName("actionExport_Report")
        self.actionSupport_Cases = QtWidgets.QAction(MainWindow)
        self.actionSupport_Cases.setObjectName("actionSupport_Cases")
        self.menuFile.addAction(self.actionExport_Report)
        self.menuTest.addAction(self.actionSupport_Cases)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTest.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Test Tool"))
        self.gbox_source_code.setTitle(_translate("MainWindow", "Source Code To Test"))
        self.txt_source_code.setPlaceholderText(_translate("MainWindow", "Source Code"))
        self.gbox_run_test.setTitle(_translate("MainWindow", "Run Test"))
        self.sp_test_cases_pool_count.setSuffix(_translate("MainWindow", "  pool"))
        self.btn_import_code.setText(_translate("MainWindow", "➤"))
        self.gbox_fixed_code.setTitle(_translate("MainWindow", "Fixed Code"))
        self.gbox_test_cases.setTitle(_translate("MainWindow", "Test Cases"))
        self.gbox_tested_lines.setTitle(_translate("MainWindow", "Tested Code Lines"))
        self.checkbox_support_case_str.setText(_translate("MainWindow", "String"))
        self.btn_support_case_add.setText(_translate("MainWindow", "➕"))
        self.btn_support_case_done.setText(_translate("MainWindow", "✓"))
        self.btn_support_case_clear_cases.setText(_translate("MainWindow", "CLEAR ALL"))
        self.pb_test_rate.setFormat(_translate("MainWindow", "%p % of the test is complete, please wait"))
        self.label_2.setText(_translate("MainWindow", "Test Case Statistics"))
        self.lbl_branched_count.setText(_translate("MainWindow", "Branched Count:"))
        self.lbl_tested_line_count.setText(_translate("MainWindow", "Tested Line Count:"))
        self.label.setText(_translate("MainWindow", "Coverage Rate: "))
        self.progressBar_coverage_rate.setFormat(_translate("MainWindow", "%p %"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTest.setTitle(_translate("MainWindow", "Test"))
        self.actionExport_Report.setText(_translate("MainWindow", "Export Report"))
        self.actionSupport_Cases.setText(_translate("MainWindow", "Support Cases"))
